N = 100;
n = 0:N-1;
g = exp(-0.5 * n);
h = sin((2*pi*n)/(N/2));
gh = conv(g, h);
L = 512;
w = -pi:2*pi/(L-1):pi;
G = freqz(g, 1, w);
H = freqz(h, 1, w);
df = w(2) - w(1);
energy_time = sum(abs(g).^2 + abs(h).^2);
energy_freq = (1/(2*pi)) * sum(abs(G).^2 .* abs(H).^2) * df;
figure(1);
subplot(2,1,1);
stem(n, abs(g).^2 + abs(h).^2);
title('Time-Domain Energy Distribution (g^2(n) + h^2(n))');
xlabel('Time Index (n)');
ylabel('Magnitude^2');
grid on;
subplot(2,1,2);
plot(w/pi, abs(G).^2 ./ energy_freq + abs(H).^2 ./ energy_freq);
title('Normalized Frequency-Domain Energy Distribution ((|G(w)|^2 + |H(w)|^2) / Total Energy)');
xlabel('Normalized Frequency (f / π)');
ylabel('Normalized Magnitude^2');
grid on;
